server {
    listen 80;
    server_name _;

    location /download/bridge/ {
        alias /usr/share/nginx/html/download/bridge/;
        autoindex off;
        add_header Content-Disposition 'attachment';
        add_header X-Content-Type-Options nosniff;
    }

    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }

    location / {
        return 404;
    }
}
